filter:
  excluded_paths:
    - 'tests/'
    - 'vendor/'

build:
  dependencies:
    override:
      - composer self-update --no-interaction --no-progress
      - composer remove squizlabs/php_codesniffer friendsofphp/php-cs-fixer vimeo/psalm phpstan/phpstan --dev --no-interaction --no-progress --no-update
      - composer install --no-interaction --no-progress
  nodes:
    php:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - command: vendor/bin/phpunit --testdox --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover
