language: php

dist: xenial

# php compatibility
php: ["7.0", "7.1", "7.2", "7.3", "7.4"]

before_script:
  - phpenv config-rm xdebug.ini || true
  - test $TRAVIS_PHP_VERSION == "7.0" && composer remove vimeo/psalm phpstan/phpstan --dev --no-interaction --no-progress --no-update || true
  - travis_retry composer install --no-interaction --no-progress --prefer-dist

script:
  - vendor/bin/phpcs -sp src/ tests/
  - vendor/bin/php-cs-fixer fix --using-cache=no --dry-run --verbose
  - vendor/bin/phpunit --verbose
  - test $TRAVIS_PHP_VERSION != "7.0" && vendor/bin/phpstan analyse --no-progress --level max src/ tests/ || true
  - test $TRAVIS_PHP_VERSION != "7.0" && vendor/bin/psalm --no-progress || true

notifications:
  email:
    if: branch = master
