language: php

dist: xenial

# php compatibility
php: ["7.0", "7.1", "7.2", "7.3", "7.4"]

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer install --no-interaction --no-progress --prefer-dist

script:
  - mkdir -p build/tests/
  - vendor/bin/phplint
  - vendor/bin/phpcs -sp src/ tests/
  - vendor/bin/php-cs-fixer fix --using-cache=no --dry-run --verbose
  - vendor/bin/phpunit --testdox --verbose
  - vendor/bin/phpstan.phar analyse --no-progress --level max src/ tests/

notifications:
  email:
    if: branch = master
